server:
  port: 9192
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Root@1992
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  file.name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.student.restapi: DEBUG
    org.hibernate: DEBUG